begin
	AGREGAR_REGIONES('LORSON PAIS');
    AGREGAR_REGIONES('PAIS naiko');
	AGREGAR_DIRECCIONES('LORSON CALLE',777);
    AGREGAR_DIRECCIONES('CALLE naiko',666);
	AGREGAR_COMUNAS('LORSON COMUNA',1,1);
    AGREGAR_COMUNAS('COMUNA naiko',2,2);
    --
   	AGREGAR_TIPO_CUOTAS('ORDINARIA',1000);
	AGREGAR_TIPO_CUOTAS('EXTRA ORDINARIA',2000);
	AGREGAR_SERVICIOS('COMEDOR DE PAN');
    AGREGAR_SERVICIOS('lamedor DE pan');
	AGREGAR_CUOTAS(1,0,'01-01-2025',1);
    AGREGAR_CUOTAS(2,0,'01-01-2025',2);
    --
    AGREGAR_USUARIOS(1,'nicolas','USUARIO','MONTAMINOS','URETRA',1,'LORONSONLAND@GMAIL.COM',1111,1,0);
    AGREGAR_USUARIOS(2,'nicolas','USUARIO','robles','alargado',1,'sadpapu@GMAIL.COM',666,2,0);
    AGREGAR_PREDIOS(5,50,0,1);
    AGREGAR_PREDIOS(6,125,0,2);
    --
    AGREGAR_SUBZONAS('PIEZA DE LORSON');
	AGREGAR_ZONAS('CASA DE LORSON',1,1);
	AGREGAR_SECTORES('POBLACION DE LORSON',1);
    AGREGAR_SUBZONAS('PIEZA DE naiko');
	AGREGAR_ZONAS('CASA DE naiko',2,2);
	AGREGAR_SECTORES('POBLACION DE naiko(rankagua)',2);
	--
	AGREGAR_CANALES('canal DE LORSON',50,1);
	AGREGAR_DIRECTIVAS('COME PANES',1);
	AGREGAR_PRESIDENTES('NICOLAS','MONTAMINOS','URETRA',1);
    AGREGAR_CANALES('canal DE LORSON',100,2);
	AGREGAR_DIRECTIVAS('COME PANES',2);
	AGREGAR_PRESIDENTES('NICOLAS','MONTAMINOS','URETRA',2);
	--
	VINCULAR_PREDIO_CANALES(1,1,1);
    VINCULAR_PREDIO_CANALES(1,2,2);
    --
    AGREGAR_PROYECTOS('FABRICA LADRILLOS','UNA FABRICA LADRILLOS','01-01-2024','01-01-2025','ACTIVO',1);
	AGREGAR_COMPUERTAS(255,'PUERTA DEL BAÑO DE LORSON',1);
	AGREGAR_CELADORES('NICOLITO','MONTAMINOS','IMBECIL',1);
    AGREGAR_PROYECTOS('FABRICA monster','UNA FABRICA de mosnter','01-01-2024','01-01-2025','inactivo',2);
	AGREGAR_COMPUERTAS(2565,'guitalla naiko',2);
	AGREGAR_CELADORES('naikolito','aña','rodriguez',2);
	--
end;