begin
	AGREGAR_REGIONES('LORSON PAIS');
	AGREGAR_DIRECCIONES('LORSON CALLE',777);
	AGREGAR_COMUNAS('LORSON COMUNA',1,1);
end;

BEGIN
	AGREGAR_TIPO_CUOTAS('ORDINARIA',10000);
	AGREGAR_TIPO_CUOTAS('EXTRA ORDINARIA',10000);
	AGREGAR_SERVICIOS('COMEDOR DE PAN');
	AGREGAR_CUOTAS(2,0,'01-01-2025',1);
END;

BEGIN
	AGREGAR_USUARIOS(1,'USUARIO','NICOLAS','MONTAMINOS','URETRA',1,'LORONSONLAND@GMAIL.COM',1111,1,0);
	AGREGAR_PREDIOS(1,1000,0,1);
END;

BEGIN
	AGREGAR_SUBZONAS('PIEZA DE LORSON');
	AGREGAR_ZONAS('CASA DE LORSON',1,1);
	AGREGAR_SECTORES('POBLACION DE LORSON',1);
END;


BEGIN
	AGREGAR_CANALES('WATER DE LORSON',50,1);
	AGREGAR_DIRECTIVAS('COME PANES',1);
	AGREGAR_PRESIDENTES('NICOLAS','MONTAMINOS','URETRA',1);
END;

INSERT INTO SA_JS_JO_NR_DETALLE_SERVICIO_CANALES(COD_SERVICIO,COD_CANAL)
VALUES(1,1);
INSERT INTO SA_JS_JO_NR_DETALLE_PREDIO_CANALES(COD_PREDIO,COD_CANAL)
VALUES(1,1);

BEGIN
	AGREGAR_PROYECTOS('FABRICA LADRILLOS','UNA FABRICA LADRILLOS','01-01-2024','01-01-2025','ACTIVO',1);
	AGREGAR_COMPUERTAS(255,'PUERTA DEL BAÑO DE LORSON',1);
	AGREGAR_CELADORES('NICOLITO','MONTAMINOS','IMBECIL',1);
END;

-- PRUEBAS TRIGGERS

BEGIN
	ACTUALIZAR_TIPO_CUOTAS(2,'EXTRA ORDINARIA',20000);--BIEN
END;

BEGIN
	ACTUALIZAR_PREDIOS(1,44,100,0,1);--BIEN
END;


BEGIN
	PAGAR(1,750000);
END;

---

begin
    agregar_predios(9,10,100000,10);
end;

begin
    agregar_canales('canal 1',10,1);
    agregar_canales('canal 2',20,1);
end;

insert into sa_js_jo_nr_detalle_predio_canales(cod_predio,cod_canal) values(10,2);
insert into sa_js_jo_nr_detalle_predio_canales(cod_predio,cod_canal) values(10,3);

begin
    actualizar_predios(10,9,10,100000,10);
end;